### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by tischi** [mobie/bigdataviewer-n5#2]
@KateMoreva @constantinpape 

Hi @imagejan, could you please help us getting this repo into the scijava maven repository?

**Comment by imagejan** [comment]
Hi @tischi,

a few comments first:
* the contributors listed in your `pom.xml` (@tischi and @K-Meech) don't seem to agree with the commit authors in this repository,
* you depend on at least one `SNAPSHOT` version and skip the enforcer.

You might to fix these issues before starting to *deploy RELEASE versions* of your artifacts. Nevertheless, you can already run [`github-actionify.sh`](https://github.com/scijava/scijava-scripts/blob/master/github-actionify.sh) on your repository. (Of course, I can do it for you, but it might be more useful for you to go through the process once yourself, because it's really simple now and doesn't require local credentials anymore.)

The only thing required to be done is that @ctrueden or @hinerm add the SciJava secrets to the `mobie` organization on GitHub. That's not something I can do, but is required only once for each org, and all future repositories in the same org will benefit from it 🙂 (It'll require that you temporarily grant admin access to either Mark or Curtis.)

**Comment by ctrueden** [comment]
@tischi I've got credentials for mobie all set to go. Just add me as admin to the mobie org, and I'll assign them.

**Comment by tischi** [comment]
@constantinpape again, I cannot find the button to do this. Could it be that I do not have all the rights for this organization? Could you please add `ctrueden` as an admin (and also myself in case I am not an admin)?

**Comment by constantinpape** [comment]
> @constantinpape again, I cannot find the button to do this. Could it be that I do not have all the rights for this organization? Could you please add `ctrueden` as an admin (and also myself in case I am not an admin)?

I am pretty sure you are admin. Anyway, I will add curtis and check that you are admin.

**Comment by constantinpape** [comment]
@ctrueden I have invited you as MoBIE org member; once you accept I will give you admin rights on the relevant repos.
(I think this should be sufficient, otherwise I could also bump you to owner.)

@tischi you are an owner and the way to do this is:
`Go to https://github.com/mobie -> People -> Invite member`
Then, in the repository you go to `Settings->Manage access`

**Comment by imagejan** [comment]
Inviting directly as an owner is usually the easiest (as long as you trust Curtis ;-), and then Curtis can remove himself after adding the secrets.

> admin rights on the relevant repos.

The secrets are added to the _organization_, not to a single repository.

**Comment by constantinpape** [comment]
I see, thanks for the clarification @imagejan. I will upgrade Curtis to owner once he accepted the invite then :).

Edit: it's possible to update the invitation, so once @ctrueden accepts he'll have owner permissions.

**Comment by constantinpape** [comment]
We decided we only need https://github.com/mobie/bigdataviewer-imageloader/issues/14
